features:
  logmel_v1:
    type: librosa
    parameters:
      sample_rate: 16000
      n_fft: 1024
      hop_length: 320
      n_mels: 64
      fmin: 20.0
      fmax: 8000.0
      top_db: 80.0
  logmel_panns_v1:
    type: panns
    parameters:
      sample_rate: 32000
      n_fft: 1024
      hop_length: 320
      n_mels: 64
      fmin: 50.0
      fmax: 14000.0
      top_db: 80.0
