"""Calibrate the frozen DataSEC coarse head with dev-only temperature scaling."""

from __future__ import annotations

import argparse
import json
import struct
import sys
import zlib
from pathlib import Path

import numpy as np
import torch
import yaml

from ml.datasets.datasec import DataSECLabelSpace
from ml.evaluation.calibration import (
    CalibrationBin,
    calibration_bins,
    expected_calibration_error,
    fit_temperature,
)
from ml.models import HierarchicalAudioClassifier, PannsCNN14Encoder
from ml.taxonomy import load_taxonomy
from scripts.train_classifier import ROOT, build_loaders, load_rows

CONFIG_PATH = ROOT / "ml" / "configs" / "calibration.yaml"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Calibrate the frozen DataSEC coarse classifier.")
    parser.add_argument("run_dir", type=Path)
    parser.add_argument("--device", default="cuda")
    return parser.parse_args()


def load_config(path: Path) -> dict[str, float | int]:
    """Load the reviewed calibration settings instead of embedding them in the CLI."""
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))["classifier_ece"]
    return {
        "bins": int(raw["bins"]),
        "max_iterations": int(raw["temperature"]["max_iterations"]),
        "learning_rate": float(raw["temperature"]["learning_rate"]),
    }


def collect_coarse_logits(
    model: HierarchicalAudioClassifier, loader: torch.utils.data.DataLoader, device: torch.device
) -> tuple[np.ndarray, np.ndarray]:
    """Collect fixed coarse logits once; test logits are never used while fitting temperature."""
    model.to(device).eval()
    logits: list[np.ndarray] = []
    targets: list[np.ndarray] = []
    with torch.inference_mode():
        for features, coarse, _ in loader:
            values, _ = model(features.to(device, non_blocking=True))
            logits.append(values.cpu().numpy())
            targets.append(coarse.numpy())
    return np.concatenate(logits), np.concatenate(targets)


def format_value(value: float) -> str:
    """Keep empty-bin measurements explicit rather than silently replacing them with zero."""
    return "—" if not np.isfinite(value) else f"{value:.6f}"


def report_text(
    *, run_dir: Path, temperature: float, before: float, after: float, rows: list[CalibrationBin]
) -> str:
    """Render the D5 measurement, including all 15 post-calibration reliability bins."""
    warning = [row for row in rows if 0 < row.count < 10]
    lines = [
        "# ECE calibration — DataSEC coarse head",
        "",
        f"> Generated by `scripts.calibrate_classifier {run_dir}`. "
        "Temperature was fit on dev only.",
        "",
        f"- Run: `{run_dir.name}`",
        f"- Temperature (locked from dev): `{temperature:.8f}`",
        f"- Test ECE before scaling (T=1): `{before:.6f}`",
        f"- Test ECE after scaling: `{after:.6f}`",
        "- Scope: coarse head only (22-way); subclass head was not calibrated.",
        "",
        "## Test reliability bins after dev-only temperature scaling",
        "",
        "| Bin | Confidence | Accuracy | Items |",
        "|---|---:|---:|---:|",
    ]
    lines.extend(
        f"| ({row.lower:.4f}, {row.upper:.4f}] | {format_value(row.confidence)} | "
        f"{format_value(row.accuracy)} | {row.count} |"
        for row in rows
    )
    if warning:
        lines += [
            "",
            f"⚠️ {len(warning)} non-empty bin(s) contain fewer than 10 items; "
            "interpret them cautiously.",
        ]
    return "\n".join(lines) + "\n"


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    """Encode one checksummed PNG chunk using only the Python standard library."""
    prefix = struct.pack(">I", len(payload)) + kind + payload
    return prefix + struct.pack(">I", zlib.crc32(kind + payload))


def write_png(image: np.ndarray, output: Path) -> None:
    """Write an RGB PNG without adding an unreviewed plotting dependency to the environment."""
    height, width, channels = image.shape
    if image.dtype != np.uint8 or channels != 3:
        raise ValueError("PNG image must be uint8 [height, width, 3]")
    raw = b"".join(b"\0" + row.tobytes() for row in image)
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", header)
        + _png_chunk(b"IDAT", zlib.compress(raw, level=9))
        + _png_chunk(b"IEND", b"")
    )


def reliability_plot(rows: list[CalibrationBin], output: Path) -> None:
    """Draw accuracy bars plus a diagonal reference; exact bin counts stay in the Markdown table."""
    height, width = 480, 640
    left, right, top, bottom = 60, 600, 30, 420
    image = np.full((height, width, 3), 255, dtype=np.uint8)
    image[bottom : bottom + 2, left:right] = (0, 0, 0)
    image[top:bottom, left : left + 2] = (0, 0, 0)
    for offset in range(min(right - left, bottom - top)):
        image[bottom - offset, left + offset] = (80, 80, 80)
    for row in rows:
        if not row.count:
            continue
        center = left + round(row.confidence * (right - left))
        bar_width = max(4, round((right - left) / len(rows) * 0.7))
        start, stop = max(left, center - bar_width // 2), min(right, center + bar_width // 2)
        bar_top = bottom - round(row.accuracy * (bottom - top))
        image[bar_top:bottom, start:stop] = (47, 110, 184)
    write_png(image, output)


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    args = parse_args()
    if args.device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    run_dir = args.run_dir.resolve()
    manifest = json.loads((run_dir / "manifest.json").read_text(encoding="utf-8"))
    if not manifest.get("complete"):
        raise SystemExit(f"Run is incomplete: {run_dir}")
    config = load_config(CONFIG_PATH)
    taxonomy = load_taxonomy(ROOT / "ml" / "configs" / "taxonomy.yaml")
    labels = DataSECLabelSpace.from_taxonomy(taxonomy)
    loaders = build_loaders(
        load_rows(),
        labels,
        batch_size=int(manifest["config"]["batch_size"]),
        sampler_mode="uniform",
    )
    checkpoint = torch.load(
        run_dir / manifest["best_checkpoint"], map_location="cpu", weights_only=True
    )
    model = HierarchicalAudioClassifier(
        PannsCNN14Encoder(),
        num_coarse=len(labels.coarse_ids),
        num_subclass=len(labels.subclass_ids),
    )
    model.load_state_dict(checkpoint["model_state"], strict=True)
    device = torch.device(args.device)
    dev_logits, dev_targets = collect_coarse_logits(model, loaders["validation"], device)
    fit = fit_temperature(
        dev_logits,
        dev_targets,
        max_iterations=int(config["max_iterations"]),
        learning_rate=float(config["learning_rate"]),
    )
    test_logits, test_targets = collect_coarse_logits(model, loaders["test"], device)
    before_rows = calibration_bins(
        test_logits, test_targets, temperature=1.0, bins=int(config["bins"])
    )
    after_rows = calibration_bins(
        test_logits, test_targets, temperature=fit.temperature, bins=int(config["bins"])
    )
    before, after = expected_calibration_error(before_rows), expected_calibration_error(after_rows)
    stem = "ece_datasec_20260923"
    output = ROOT / "docs" / "measurements" / f"{stem}.md"
    report = report_text(
        run_dir=run_dir,
        temperature=fit.temperature,
        before=before,
        after=after,
        rows=after_rows,
    )
    output.write_text(report, encoding="utf-8")
    plot_path = output.with_suffix(".png")
    reliability_plot(after_rows, plot_path)
    print(
        json.dumps(
            {
                "temperature": fit.temperature,
                "ece_before": before,
                "ece_after": after,
                "report": str(output),
                "plot": str(plot_path),
            }
        )
    )


if __name__ == "__main__":
    main()
