"""Verify the official PANNs checkpoint and write its measurement artifact."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from ml.models.panns import PannsCNN14Encoder

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CHECKPOINT = ROOT / "artifacts" / "checkpoints" / "Cnn14_mAP=0.431.pth"
DEFAULT_OUTPUT = ROOT / "docs" / "measurements" / "panns_checkpoint_20260923.md"
EXPECTED_MD5 = "595633ac2d1cac7ef04ebf70e2fee4e4"


def file_hash(path: Path, algorithm: str) -> str:
    digest = hashlib.new(algorithm)
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    checkpoint = args.checkpoint.resolve()
    md5 = file_hash(checkpoint, "md5")
    if md5 != EXPECTED_MD5:
        raise SystemExit(f"MD5 mismatch: expected {EXPECTED_MD5}, got {md5}")
    sha256 = file_hash(checkpoint, "sha256")
    report = PannsCNN14Encoder().load_audioset_pretrained(checkpoint)
    args.output.write_text(
        "\n".join(
            [
                "# Official PANNs checkpoint verification",
                "",
                "> Generated by `python -m scripts.report_panns_checkpoint`. Do not edit values by hand.",  # noqa: E501
                "",
                "| Field | Value |",
                "|---|---|",
                "| Zenodo record | `3576403` |",
                "| File | `Cnn14_mAP=0.431.pth` |",
                "| License | `not recorded` (Zenodo Rights field is blank; do not infer a license) |",  # noqa: E501
                f"| Bytes | {checkpoint.stat().st_size:,} |",
                f"| MD5 | `{md5}` (matches official) |",
                f"| SHA-256 | `{sha256}` |",
                f"| Checkpoint tensors | {report.checkpoint_tensors} |",
                f"| Checkpoint parameters | {report.checkpoint_parameters:,} |",
                f"| Transplanted tensors | {report.transplanted_tensors} |",
                f"| Transplanted parameters | {report.transplanted_parameters:,} |",
                f"| Transplanted parameter share | {report.parameter_fraction:.4%} |",
                "",
                "Only `conv_block1...conv_block6` are mapped to the local encoder's six blocks.",
                "The required train-DataSEC normalization replacing official `bn0` awaits B2 features; do not claim it is active yet.",  # noqa: E501
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(args.output.relative_to(ROOT))


if __name__ == "__main__":
    main()
