"""Generate the data inventory from frozen manifests and split assignments."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

from ml.dataops.datasec_labels import labels_by_file_id
from ml.taxonomy import load_taxonomy

ROOT = Path(__file__).resolve().parents[1]
MANIFESTS = ROOT / "data" / "manifests"
SPLITS = ROOT / "data" / "splits"
OUTPUT = ROOT / "docs" / "data_inventory.md"
TAXONOMY = ROOT / "ml" / "configs" / "taxonomy.yaml"
SPLIT_ORDER = ("train", "validation", "test", "not_in_split")


def format_hours(seconds: float) -> str:
    return f"{seconds / 3600:.3f}"


def datasec_by_class() -> pd.DataFrame:
    inventory = pd.read_csv(MANIFESTS / "datasec_inventory.csv")
    assignments = pd.read_csv(SPLITS / "datasec_classification.csv")
    labels = labels_by_file_id(MANIFESTS / "datasec_inventory.csv", load_taxonomy(TAXONOMY))
    inventory["class_id"] = inventory["file_id"].map(lambda file_id: labels[str(file_id)][0])
    merged = inventory.merge(
        assignments[["file_id", "split"]], on="file_id", how="left", validate="one_to_one"
    )
    merged["split"] = merged["split"].fillna("not_in_split")
    rows: list[dict[str, str | int]] = []
    for class_id, group in merged.groupby("class_id", sort=True):
        row: dict[str, str | int] = {
            "class_id": class_id,
            "files": len(group),
            "hours": format_hours(float(group["duration_s"].sum())),
        }
        for split in SPLIT_ORDER:
            subset = group[group["split"] == split]
            row[split] = f"{len(subset)} / {format_hours(float(subset['duration_s'].sum()))}"
        rows.append(row)
    return pd.DataFrame(rows)


def datased_by_class() -> pd.DataFrame:
    recordings = pd.read_csv(MANIFESTS / "datased_recordings.csv")
    assignments = pd.read_csv(SPLITS / "datased_polyphonic.csv")
    events = pd.read_csv(ROOT / "data" / "annotations" / "datased_polyphonic_events.csv")
    merged = recordings.merge(
        assignments[["recording_id", "split"]], on="recording_id", validate="one_to_one"
    )
    if len(merged) != len(recordings):
        raise ValueError("DataSED inventory and frozen split do not have identical recording IDs.")
    coverage = (
        events[["recording_id", "class_id"]]
        .drop_duplicates()
        .merge(merged, on="recording_id", validate="many_to_one")
    )
    rows: list[dict[str, str | int]] = []
    for class_id, group in coverage.groupby("class_id", sort=True):
        row: dict[str, str | int] = {
            "class_id": class_id,
            "recordings": len(group),
            "coverage_hours": format_hours(float(group["duration_s"].sum())),
        }
        for split in SPLIT_ORDER:
            subset = group[group["split"] == split]
            row[split] = f"{len(subset)} / {format_hours(float(subset['duration_s'].sum()))}"
        rows.append(row)
    return pd.DataFrame(rows)


def split_totals(
    recordings: pd.DataFrame, assignments: pd.DataFrame, id_column: str
) -> pd.DataFrame:
    merged = recordings.merge(
        assignments[[id_column, "split"]], on=id_column, how="left", validate="one_to_one"
    )
    merged["split"] = merged["split"].fillna("not_in_split")
    totals = (
        merged.groupby("split", sort=False)
        .agg(files=(id_column, "size"), duration_s=("duration_s", "sum"))
        .reindex(SPLIT_ORDER)
        .reset_index()
    )
    totals["hours"] = totals.pop("duration_s").map(format_hours)
    return totals


def table(frame: pd.DataFrame) -> list[str]:
    columns = list(frame.columns)
    lines = ["| " + " | ".join(columns) + " |", "|" + "|".join("---:" for _ in columns) + "|"]
    for row in frame.itertuples(index=False, name=None):
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return lines


def main() -> None:
    datasec_inventory = pd.read_csv(MANIFESTS / "datasec_inventory.csv")
    datased_recordings = pd.read_csv(MANIFESTS / "datased_recordings.csv")
    datasec_splits = pd.read_csv(SPLITS / "datasec_classification.csv")
    datased_splits = pd.read_csv(SPLITS / "datased_polyphonic.csv")
    datasec, datased = datasec_by_class(), datased_by_class()
    lines = [
        "# Data inventory",
        "",
        "> Generated by `python -m scripts.report_data_inventory` from inventories and frozen split CSVs.",  # noqa: E501
        "> Do not edit numeric values by hand.",
        "",
        f"- Generated: `{datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}`",
        "- Units in class tables: `files / hours`; hours are decoded recording duration.",
        "",
        "## DataSEC classification",
        "",
        "| class_id | files | hours | train (files / hours) | validation (files / hours) | test (files / hours) |",  # noqa: E501
        "|---|---:|---:|---:|---:|---:|",
    ]
    for row in datasec.itertuples(index=False):
        lines.append(
            f"| `{row.class_id}` | {row.files} | {row.hours} | {row.train} | {row.validation} | {row.test} |"  # noqa: E501
        )
    lines.extend(
        [
            "",
            "### DataSEC totals",
            "",
            *table(split_totals(datasec_inventory, datasec_splits, "file_id")),
        ]
    )
    lines.extend(
        [
            "",
            "## DataSED polyphonic coverage",
            "",
            "A recording with multiple labels appears once for each covered class, so coverage hours",  # noqa: E501
            "are not additive across rows. This is recording coverage, not annotated event duration.",  # noqa: E501
            "",
            "| class_id | recordings | coverage_hours | train (files / hours) | validation (files / hours) | test (files / hours) |",  # noqa: E501
            "|---|---:|---:|---:|---:|---:|",
        ]
    )
    for row in datased.itertuples(index=False):
        lines.append(
            f"| `{row.class_id}` | {row.recordings} | {row.coverage_hours} | {row.train} | {row.validation} | {row.test} |"  # noqa: E501
        )
    lines.extend(
        [
            "",
            "### DataSED totals",
            "",
            *table(split_totals(datased_recordings, datased_splits, "recording_id")),
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
