"""Select a DataSEC consistency-loss weight from validation-only artifacts."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

import yaml

from scripts.train_classifier import ROOT


@dataclass(frozen=True)
class Candidate:
    """Best primary-metric checkpoint and its validation metrics for one weight."""

    run_dir: Path
    weight: float
    epoch: int
    coarse_f1: float
    subclass_supported_f1: float
    parent_consistency: float


@dataclass(frozen=True)
class Selection:
    """Validation-only sweep decision, retaining rejected candidates for reporting."""

    baseline: Candidate
    eligible: tuple[Candidate, ...]
    selected: Candidate
    coarse_cutoff: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_dirs", type=Path, nargs="+")
    parser.add_argument(
        "--config",
        type=Path,
        default=ROOT / "ml" / "configs" / "consistency_sweep.yaml",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "measurements" / "consistency_sweep_datasec_20260923.md",
    )
    return parser.parse_args()


def load_candidate(run_dir: Path) -> Candidate:
    """Read the validation record belonging to the primary-metric checkpoint."""
    run_dir = run_dir.resolve()
    manifest = json.loads((run_dir / "manifest.json").read_text(encoding="utf-8"))
    history = json.loads((run_dir / "logs" / "history.json").read_text(encoding="utf-8"))["epochs"]
    if manifest.get("primary_metric") != "coarse_macro_f1":
        raise ValueError(f"Unexpected primary metric in {run_dir.name}")
    best = max(history, key=lambda item: float(item["validation"]["coarse_macro_f1"]))
    validation = best["validation"]
    return Candidate(
        run_dir=run_dir,
        weight=float(manifest["config"]["loss_weights"]["consistency"]),
        epoch=int(best["epoch"]),
        coarse_f1=float(validation["coarse_macro_f1"]),
        subclass_supported_f1=float(validation["subclass_macro_f1_supported"]),
        parent_consistency=float(validation["parent_consistency_rate"]),
    )


def load_config(path: Path) -> dict[str, float]:
    """Load the selection constants locked by the D4 task specification."""
    config = yaml.safe_load(path.read_text(encoding="utf-8"))
    return {key: float(value) for key, value in config.items()}


def select_candidate(candidates: list[Candidate], config: dict[str, float]) -> Selection:
    """Apply the D4 two-step guardrail and deterministic validation-only tie break."""
    baseline = next((item for item in candidates if item.weight == 0.0), None)
    if baseline is None:
        raise ValueError("D4 requires the lambda=0 baseline")
    cutoff = baseline.coarse_f1 - config["coarse_guardrail_drop"]
    eligible = tuple(item for item in candidates if item.coarse_f1 >= cutoff)
    if not eligible:
        raise ValueError("No candidate survived the coarse-F1 guardrail")
    highest_parent = max(item.parent_consistency for item in eligible)
    tied = [
        item
        for item in eligible
        if highest_parent - item.parent_consistency < config["parent_consistency_tie"]
    ]
    selected = min(
        tied,
        key=lambda item: (
            -item.subclass_supported_f1,
            abs(item.weight - config["default_consistency_weight"]),
        ),
    )
    return Selection(baseline, eligible, selected, cutoff)


def test_metrics(run_dir: Path) -> dict[str, float | int]:
    """Require that test evaluation happened only after the selected run was frozen."""
    metrics = json.loads((run_dir / "metrics.json").read_text(encoding="utf-8"))
    if "test" not in metrics:
        raise ValueError(f"Selected run has no recorded test evaluation: {run_dir.name}")
    return metrics["test"]


def render_report(
    candidates: list[Candidate], selection: Selection, test: dict[str, float | int]
) -> str:
    """Render the reproducible D4 sweep artifact without selecting on test scores."""
    eligible = set(selection.eligible)
    lines = [
        "# Consistency-loss sweep — DataSEC",
        "",
        "> Generated by `scripts.report_consistency_sweep` from frozen run histories and "
        "the single test evaluation of the selected checkpoint.",
        "",
        "## Validation-only selection",
        "",
        f"- Baseline λ=0 coarse macro-F1: **{selection.baseline.coarse_f1:.6f}**",
        f"- Guardrail cutoff (baseline − 0.020000): **{selection.coarse_cutoff:.6f}**",
        "- Selection then maximizes parent-consistency; values within 0.005 are tied and "
        "use supported subclass macro-F1, then distance to λ=0.5.",
        "",
        "| λ_cons | Run | Best epoch | Dev coarse macro-F1 | Dev parent-consistency | "
        "Dev subclass macro-F1 (n≥10) | Guardrail |",
        "|---:|---|---:|---:|---:|---:|---|",
    ]
    for candidate in sorted(candidates, key=lambda item: item.weight):
        guardrail = "eligible" if candidate in eligible else "rejected"
        lines.append(
            f"| {candidate.weight:.2f} | `{candidate.run_dir.name}` | {candidate.epoch} | "
            f"{candidate.coarse_f1:.6f} | {candidate.parent_consistency:.6f} | "
            f"{candidate.subclass_supported_f1:.6f} | {guardrail} |"
        )
    lines += [
        "",
        f"**Selected λ_cons = {selection.selected.weight:.2f}** "
        f"(`{selection.selected.run_dir.name}`) "
        "using validation only. Test was opened exactly once afterwards for this checkpoint.",
        "",
        "## Test metrics of selected checkpoint",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Coarse macro-F1 | {float(test['coarse_macro_f1']):.6f} |",
        f"| Subclass macro-F1 (all 28 nodes) | {float(test['subclass_macro_f1_all']):.6f} |",
        f"| Subclass macro-F1 (n_test ≥ 10) | {float(test['subclass_macro_f1_supported']):.6f} |",
        f"| Parent-consistency | {float(test['parent_consistency_rate']):.6f} |",
        "",
        "The two subclass macro-F1 values follow ADR-0006 §3; low-support node details are "
        "in `d4_consistency_selected_test_20260923.md`.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    config = load_config(args.config.resolve())
    candidates = [load_candidate(run_dir) for run_dir in args.run_dirs]
    selection = select_candidate(candidates, config)
    report = render_report(candidates, selection, test_metrics(selection.selected.run_dir))
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report, encoding="utf-8")
    print(f"selected: {selection.selected.run_dir.name} (lambda={selection.selected.weight:g})")
    print(f"report: {output}")


if __name__ == "__main__":
    main()
