"""Report frozen DataSEC classifier per-class metrics from one test inference pass."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import f1_score

from ml.datasets.datasec import DataSECLabelSpace
from ml.models import HierarchicalAudioClassifier, PannsCNN14Encoder
from ml.taxonomy import load_taxonomy
from scripts.train_classifier import ROOT, build_loaders, load_rows, supported_subclass_ids

LOW_SUPPORT_THRESHOLD = 10


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Report frozen DataSEC classifier per-class test metrics."
    )
    parser.add_argument("run_dir", type=Path)
    parser.add_argument("--device", default="cuda")
    return parser.parse_args()


def class_rows(
    class_ids: tuple[str, ...],
    targets: np.ndarray,
    predictions: np.ndarray,
    *,
    score_targets: np.ndarray | None = None,
    score_predictions: np.ndarray | None = None,
) -> list[dict[str, int | float | str]]:
    """Return stable per-class rows, optionally calculating F1 on a defined subset."""
    if (score_targets is None) != (score_predictions is None):
        raise ValueError("score targets and predictions must be provided together")
    score_targets = targets if score_targets is None else score_targets
    score_predictions = predictions if score_predictions is None else score_predictions
    scores = f1_score(
        score_targets,
        score_predictions,
        labels=list(range(len(class_ids))),
        average=None,
        zero_division=0,
    )
    return [
        {
            "class_id": class_id,
            "support": int((targets == index).sum()),
            "correct": int(((targets == index) & (predictions == index)).sum()),
            "f1": float(scores[index]),
        }
        for index, class_id in enumerate(class_ids)
    ]


def macro_f1(rows: list[dict[str, int | float | str]]) -> float:
    """Calculate the unweighted per-node macro-F1 represented by report rows."""
    return float(np.mean([float(row["f1"]) for row in rows]))


def score_table_lines(rows: list[dict[str, int | float | str]]) -> list[str]:
    """Render a per-class F1 table shared by coarse and supported subclass sections."""
    return [
        "| class_id | Correct | Total | F1 |",
        "|---|---:|---:|---:|",
        *[
            f"| `{row['class_id']}` | {row['correct']} | {row['support']} | {row['f1']:.6f} |"
            for row in rows
        ],
    ]


def low_support_lines(rows: list[dict[str, int | float | str]]) -> list[str]:
    """Render low-support subclass evidence without presenting unstable F1 values."""
    return [
        "| class_id | Đúng / tổng |",
        "|---|---:|",
        *[f"| `{row['class_id']}` | {row['correct']} / {row['support']} |" for row in rows],
    ]


def collect_test_predictions(
    model: HierarchicalAudioClassifier, loader: torch.utils.data.DataLoader, device: torch.device
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Run the frozen classifier once and collect both heads' targets and argmax outputs."""
    model.to(device).eval()
    coarse_targets: list[np.ndarray] = []
    coarse_predictions: list[np.ndarray] = []
    subclass_targets: list[np.ndarray] = []
    subclass_predictions: list[np.ndarray] = []
    with torch.inference_mode():
        for features, coarse, subclass in loader:
            coarse_logits, subclass_logits = model(features.to(device, non_blocking=True))
            coarse_targets.append(coarse.numpy())
            coarse_predictions.append(coarse_logits.argmax(dim=1).cpu().numpy())
            subclass_targets.append(subclass.numpy())
            subclass_predictions.append(subclass_logits.argmax(dim=1).cpu().numpy())
    return tuple(
        np.concatenate(values)
        for values in (coarse_targets, coarse_predictions, subclass_targets, subclass_predictions)
    )  # type: ignore[return-value]


def render_report(
    *,
    run_dir: Path,
    checkpoint_sha256: str,
    coarse: list[dict[str, int | float | str]],
    subclass_all: list[dict[str, int | float | str]],
    subclass_supported: list[dict[str, int | float | str]],
) -> str:
    """Render the reproducible Markdown artifact required by D3 and ADR-0006."""
    low_support = [row for row in subclass_all if int(row["support"]) < LOW_SUPPORT_THRESHOLD]
    lines = [
        "# Per-class metrics — DataSEC classifier",
        "",
        f"> Generated by `scripts.report_per_class_metrics {run_dir}` from one frozen test "
        "inference pass.",
        "",
        f"- Run: `{run_dir.name}`",
        f"- Best checkpoint SHA-256: `{checkpoint_sha256}`",
        "- Test was not used to choose a model or hyperparameter.",
        "",
        "## Macro-F1",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Coarse (22 classes) | {macro_f1(coarse):.6f} |",
        f"| Subclass (all 28 nodes) | {macro_f1(subclass_all):.6f} |",
        f"| Subclass (n_test >= 10; {len(subclass_supported)} nodes) | "
        f"{macro_f1(subclass_supported):.6f} |",
        "",
        "## Coarse classes",
        "",
    ]
    lines.extend(score_table_lines(coarse))
    lines += [
        "",
        "## Subclass classes with n_test >= 10",
        "",
    ]
    lines.extend(score_table_lines(subclass_supported))
    lines += [
        "",
        "## Low-support subclass nodes (n_test < 10)",
        "",
        "Theo ADR-0006 §4, các node này chỉ báo số tuyệt đối đúng/tổng, không báo F1 hay tỷ lệ.",
        "",
    ]
    lines.extend(low_support_lines(low_support))
    return "\n".join(lines) + "\n"


def validate_locked_metrics(
    expected: dict[str, float],
    coarse: list[dict[str, int | float | str]],
    subclass_all: list[dict[str, int | float | str]],
    subclass_supported: list[dict[str, int | float | str]],
) -> None:
    """Refuse a report if it cannot reproduce the frozen D1 macro metrics."""
    actual = {
        "coarse_macro_f1": macro_f1(coarse),
        "subclass_macro_f1_all": macro_f1(subclass_all),
        "subclass_macro_f1_supported": macro_f1(subclass_supported),
    }
    mismatches = [name for name, value in actual.items() if not np.isclose(value, expected[name])]
    if mismatches:
        raise SystemExit(f"Per-class metrics disagree with frozen D1 metrics: {mismatches}")


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    args = parse_args()
    if args.device == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")

    run_dir = args.run_dir.resolve()
    manifest = json.loads((run_dir / "manifest.json").read_text(encoding="utf-8"))
    if not manifest.get("complete"):
        raise SystemExit(f"Run is incomplete: {run_dir}")
    checkpoint_path = run_dir / manifest["best_checkpoint"]
    checkpoint = torch.load(checkpoint_path, map_location="cpu", weights_only=True)

    taxonomy = load_taxonomy(ROOT / "ml" / "configs" / "taxonomy.yaml")
    label_space = DataSECLabelSpace.from_taxonomy(taxonomy)
    rows = load_rows()
    loaders = build_loaders(
        rows,
        label_space,
        batch_size=int(manifest["config"]["batch_size"]),
        sampler_mode="uniform",
    )
    expected_supported = supported_subclass_ids(rows, label_space)
    if sorted(expected_supported) != manifest["supported_subclass_ids"]:
        raise SystemExit("Supported subclass IDs differ from the frozen run manifest")

    model = HierarchicalAudioClassifier(
        PannsCNN14Encoder(),
        num_coarse=len(label_space.coarse_ids),
        num_subclass=len(label_space.subclass_ids),
    )
    model.load_state_dict(checkpoint["model_state"], strict=True)
    results = collect_test_predictions(model, loaders["test"], torch.device(args.device))
    coarse_target, coarse_prediction, subclass_target, subclass_prediction = results
    valid = subclass_target != -1
    coarse = class_rows(label_space.coarse_ids, coarse_target, coarse_prediction)
    subclass_all = class_rows(
        label_space.subclass_ids, subclass_target[valid], subclass_prediction[valid]
    )
    supported = np.isin(subclass_target, manifest["supported_subclass_ids"])
    subclass_supported = class_rows(
        label_space.subclass_ids,
        subclass_target[valid],
        subclass_prediction[valid],
        score_targets=subclass_target[supported],
        score_predictions=subclass_prediction[supported],
    )
    supported_rows = [
        row for row in subclass_supported if int(row["support"]) >= LOW_SUPPORT_THRESHOLD
    ]
    expected_metrics = json.loads((run_dir / "metrics.json").read_text(encoding="utf-8"))["test"]
    validate_locked_metrics(expected_metrics, coarse, subclass_all, supported_rows)
    report = render_report(
        run_dir=run_dir,
        checkpoint_sha256=manifest["config"]["checkpoint_sha256"],
        coarse=coarse,
        subclass_all=subclass_all,
        subclass_supported=supported_rows,
    )
    output = ROOT / "docs" / "measurements" / "per_class_metrics_datasec_20260923.md"
    output.write_text(report, encoding="utf-8")
    print(f"report: {output}")


if __name__ == "__main__":
    main()
